sudo: required

language: python
python:
  - 3.8

services:
  - docker

install:
  #- docker build --target development --tag $USERNAME/todo-app:$TRAVIS_COMMIT .
  #- docker build --target production --tag $USERNAME/todo-app:latest .
  - docker build --target test --tag $USERNAME/todo-app:$TRAVIS_COMMIT .
  #- docker images
  
  #- docker run --env-file ./.env.template -p 5000:80 --mount type=bind,source=/devops-course-starter/src/app/,target=/devops-course-starter/src/app/ --name app todo-app:$TRAVIS_COMMIT
  #- docker run --env-file ./.env.template -p 5000:80 --mount type=bind,source=/devops-course-starter/src/app/,target=/devops-course-starter/src/app/ --name app todo-app:latest
  - docker run --env-file ./.env.test -p 5000:80 --mount type=bind,source=/devops-course-starter/src/app/,target=/devops-course-starter/src/app/ --name int-test-app todo-app:$TRAVIS_COMMIT

before_script:
  - poetry install

script:
#- docker ps | grep -q app
- docker ps | grep -q int-test-app
- poetry run pytest
- poetry run pytest test_integration_trello.py
- poetry run pytest ./test_e2e

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin; docker push $USERNAME/todo-app:latest; fi
